---
- name: Notify reboot required
  ansible.builtin.copy:
    dest: "{{ ars_bootc_reboot_marker }}"
    content: |
      {{ ansible_date_time.iso8601 }}
      bootc switch activated {{ ars_local_image_tag }}
      Run: sudo systemctl reboot
    owner: root
    group: root
    mode: "0644"
