---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - ../../../../group_vars/all.yml
  roles:
    - role: rpm_packages
    - role: dnf_repos
    - role: third_party_rpms
    - role: appimages
    - role: fonts
    - role: bootc_image
