---
driver:
  name: docker
platforms:
  - name: ars-linux-bootc-image
    image: registry.fedoraproject.org/fedora:44
    pre_build_image: true
    privileged: false
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  inventory:
    host_vars:
      ars-linux-bootc-image:
        ars_user: testuser
        ars_base_image: ghcr.io/zirconium-dev/zirconium:latest
        ars_local_image_tag: localhost/ars-linux:latest
        ars_previous_image_tag: localhost/ars-linux:previous
        ars_build_dir: /var/lib/ars-linux/build
        ars_state_dir: /var/lib/ars-linux
        ars_zdots_repo: https://github.com/pbonh/zdots.git
        ars_zdots_branch: main
        ars_zdots_install_path: /usr/share/zirconium/zdots
        ars_rpm_packages_extra: []
        ars_extra_fonts: []
        ars_npm_globals: []
        ars_containerfile_extra_lines: []
        ars_appimages: []
        ars_third_party_rpms: []
        ars_dnf_repos:
          brave-browser.repo: brave-browser.repo.j2
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
