---
# Map of "<filename>.repo" -> "<template>.j2". The bootc_image role enumerates
# this map to stage repo files into the build context.
ars_dnf_repos:
  brave-browser.repo: brave-browser.repo.j2
  docker-ce.repo: docker-ce.repo.j2
  "_copr:copr.fedorainfracloud.org:atim:starship.repo": _copr_atim_starship.repo.j2
  "_copr:copr.fedorainfracloud.org:scottames:ghostty.repo": _copr_scottames_ghostty.repo.j2
  "_copr:copr.fedorainfracloud.org:wezfurlong:wezterm-nightly.repo": _copr_wezfurlong_wezterm-nightly.repo.j2

ars_dnf_repos_dir: /etc/yum.repos.d
