---
- name: Ensure user unit dir exists
  ansible.builtin.file:
    path: "{{ ars_systemd_user_unit_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Ensure user-preset dir exists
  ansible.builtin.file:
    path: "{{ ars_systemd_user_preset_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Render chezmoi-init.service
  ansible.builtin.template:
    src: chezmoi-init.service.j2
    dest: "{{ ars_systemd_user_unit_dir }}/chezmoi-init.service"
    owner: root
    group: root
    mode: "0644"

- name: Render chezmoi-update.service
  ansible.builtin.template:
    src: chezmoi-update.service.j2
    dest: "{{ ars_systemd_user_unit_dir }}/chezmoi-update.service"
    owner: root
    group: root
    mode: "0644"

- name: Render chezmoi-update.timer
  ansible.builtin.template:
    src: chezmoi-update.timer.j2
    dest: "{{ ars_systemd_user_unit_dir }}/chezmoi-update.timer"
    owner: root
    group: root
    mode: "0644"

- name: Install tailscale-systray.service
  ansible.builtin.copy:
    src: tailscale-systray.service
    dest: "{{ ars_systemd_user_unit_dir }}/tailscale-systray.service"
    owner: root
    group: root
    mode: "0644"

- name: Render user preset
  ansible.builtin.template:
    src: 01-ars-linux.preset.j2
    dest: "{{ ars_systemd_user_preset_dir }}/{{ ars_systemd_user_preset_filename }}"
    owner: root
    group: root
    mode: "0644"
