---
- name: Ensure flatpak preinstall.d exists
  ansible.builtin.file:
    path: "{{ ars_flatpaks_preinstall_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Ensure flatpak remotes.d exists
  ansible.builtin.file:
    path: "{{ ars_flatpaks_remotes_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install flathub remote
  ansible.builtin.copy:
    src: flathub.flatpakrepo
    dest: "{{ ars_flatpaks_remotes_dir }}/flathub.flatpakrepo"
    owner: root
    group: root
    mode: "0644"

- name: Render preinstall manifest
  ansible.builtin.template:
    src: apps.preinstall.j2
    dest: "{{ ars_flatpaks_preinstall_dir }}/{{ ars_flatpaks_preinstall_filename }}"
    owner: root
    group: root
    mode: "0644"
